---
driver:
  name: vagrant
  customize:
    audio: none

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.8.12
  # You may wish to disable always updating cookbooks in CI or other testing
  # environments.
 
  # For example: always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: client
    run_list:
      - recipe[slurm-wlm::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      "slurm-wlm":
        "packages":
          "manage": "False"
        "repository":
          "uri": "http://us.archive.ubuntu.com/ubuntu/"
          "distribution": "trusty"
          "components":
            - "main"
          "key": "C0B21F32"
          "keyserver": "keyserver.ubuntu.org"
  - name: munge
    run_list:
      - recipe[slurm-wlm::munge]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: fullstack
    # This tests controller and daemon on one so that
    # daemons can start properly
    run_list:
      - recipe[slurm-wlm::default]
      - recipe[slurm-wlm::slurmctld]
      - recipe[slurm-wlm::slurmd]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      "slurm-wlm":
        "packages":
          "manage": "False"
        "repository":
          "uri": "http://us.archive.ubuntu.com/ubuntu/"
          "components":
            - "main"
          "key": "C0B21F32"
          "keyserver": "keyserver.ubuntu.org"
    driver:
      vm_hostname: alvin
  - name: power_control
    # This tests controller and daemon on one so that
    # daemons can start properly
    run_list:
      - recipe[slurm-wlm::default]
      - recipe[slurm-wlm::slurmctld]
      - recipe[slurm-wlm::power_control]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      "slurm-wlm":
        "packages":
          "manage": "False"
        "repository":
          "uri": "http://us.archive.ubuntu.com/ubuntu/"
          "components":
            - "main"
          "key": "C0B21F32"
          "keyserver": "keyserver.ubuntu.org"
    driver:
      vm_hostname: alvin
